/**
 * Regenerates the bundled place catalog and airport list (atlas-v1.md, MAP-2).
 * Sources (public domain):
 *  - Natural Earth v5.1.2 populated places (10m, simple) via the natural-earth-vector repository
 *  - Natural Earth admin-0 countries (50m) via the world-atlas npm package
 *  - OurAirports airports.csv
 * Run: npm run data:build   (needs network access to raw.githubusercontent.com)
 */
import { writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { geoCentroid } from "d3-geo";
import { feature } from "topojson-client";
import type { Topology, GeometryCollection } from "topojson-specification";

const NE_TAG = "v5.1.2";
const PLACES_URL = `https://raw.githubusercontent.com/nvkelso/natural-earth-vector/${NE_TAG}/geojson/ne_10m_populated_places_simple.geojson`;
const AIRPORTS_URL = "https://raw.githubusercontent.com/davidmegginson/ourairports-data/main/airports.csv";

type Place = { id: string; name: string; country: string; lat: number; lon: number; kind: "city" | "country" };

const round = (n: number) => Math.round(n * 1e5) / 1e5;

async function get(url: string): Promise<string> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  return res.text();
}

function parseCsvLine(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let q = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i]!;
    if (q) {
      if (c === '"' && line[i + 1] === '"') { cur += '"'; i++; }
      else if (c === '"') q = false;
      else cur += c;
    } else if (c === '"') q = true;
    else if (c === ",") { out.push(cur); cur = ""; }
    else cur += c;
  }
  out.push(cur);
  return out;
}

const places: Place[] = [];
const countriesTopo = JSON.parse(readFileSync("node_modules/world-atlas/countries-50m.json", "utf8")) as Topology;
const countries = feature(countriesTopo, countriesTopo.objects.countries as GeometryCollection<{ name: string }>);
for (const f of countries.features) {
  const name = f.properties?.name;
  if (!name) continue;
  const [lon, lat] = geoCentroid(f);
  places.push({ id: `country:${f.id ?? name}`, name, country: name, lat: round(lat), lon: round(lon), kind: "country" });
}

const geo = JSON.parse(await get(PLACES_URL)) as { features: Array<{ properties: Record<string, unknown> }> };
for (const f of geo.features) {
  const p = f.properties;
  const name = String(p.name ?? p.nameascii ?? "").trim();
  const country = String(p.adm0name ?? "").trim();
  const lat = Number(p.latitude);
  const lon = Number(p.longitude);
  if (!name || !country || !Number.isFinite(lat) || !Number.isFinite(lon)) continue;
  places.push({ id: `ne:${p.ne_id ?? `${name}|${country}`}`, name, country, lat: round(lat), lon: round(lon), kind: "city" });
}

const airports: Record<string, [number, number]> = {};
const csv = (await get(AIRPORTS_URL)).split(/\r?\n/);
const head = parseCsvLine(csv[0]!);
const col = (n: string) => head.indexOf(n);
for (const line of csv.slice(1)) {
  if (!line) continue;
  const r = parseCsvLine(line);
  const type = r[col("type")];
  const code = r[col("iata_code")] ?? "";
  if (!/^[A-Z]{3}$/.test(code) || (type !== "large_airport" && type !== "medium_airport")) continue;
  if (airports[code] && type !== "large_airport") continue;
  airports[code] = [round(Number(r[col("latitude_deg")])), round(Number(r[col("longitude_deg")]))];
}

mkdirSync("src/data", { recursive: true });
places.sort((a, b) => a.name.localeCompare(b.name) || a.country.localeCompare(b.country));
writeFileSync("src/data/places.json", JSON.stringify(places));
writeFileSync("src/data/airports.json", JSON.stringify(airports));
writeFileSync(
  "src/data/SOURCES.md",
  `# Bundled geographic data\n\nGenerated by \`npm run data:build\` on ${new Date().toISOString().slice(0, 10)}.\n\n` +
    `- \`places.json\`: ${places.filter((p) => p.kind === "city").length} populated places from [Natural Earth](https://www.naturalearthdata.com/) ${NE_TAG} ` +
    `(ne_10m_populated_places_simple) and ${places.filter((p) => p.kind === "country").length} country centroids from Natural Earth 50m admin-0 via the \`world-atlas\` package. Public domain.\n` +
    `- \`airports.json\`: ${Object.keys(airports).length} IATA codes (large and medium airports) from [OurAirports](https://ourairports.com/data/) \`airports.csv\`. Public domain.\n` +
    `- The globe outline uses \`world-atlas\` land-110m (Natural Earth, public domain) directly from node_modules.\n\n` +
    `The app never calls a geocoder or map service; these files are the only place data.\n`,
);
console.log(`places: ${places.length}, airports: ${Object.keys(airports).length}`);
